### ISSUE TITLE
The step "node-gyp rebuild" is breaking on "npm install php-pack"

### ISSUE THREAD

**Issue by dennermiranda** [acgpiano/php-pack#3]
Hello,

I've been trying to install php-pack since yesterday but I am getting the following error:

`make: Entering directory '/home/dener/Project/node_modules/php-pack/build'
  CXX(target) Release/obj.target/phppack/pack.o
In file included from ../pack.cc:17:0:
../pack.h:10:10: fatal error: node/node_object_wrap.h: No such file or directory`
` #include <node/node_object_wrap.h>`
         ` ^~~~~~~~~~~~~~~~~~~~~~~~~`
`compilation terminated.
phppack.target.mk:93: recipe for target 'Release/obj.target/phppack/pack.o' failed
make: *** [Release/obj.target/phppack/pack.o] Error 1
make: Leaving directory '/home/dener/Project/node_modules/php-pack/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dener/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/home/dener/.nvm/versions/node/v8.10.0/bin/node" "/home/dener/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok`

I am using:
Ubuntu 17.10
NVM 0.33.8
NPM 5.6.0
Node 8.10.0

I have all node-gyp dependencies.

Thanks!

**Comment by dennermiranda** [comment]
Hello again,

Fixed it using the system installation of Node, no NVM.

Thanks!

PS: sorry for the bad log above, I wasn't sure on how to properly post it on github.
